project:
  type: book

book:
  title: "Scientific writing e-book"
  author: "Ciara Norton"
  favicon: TeamShrubLogo.png
  description: An e-book to learn about scientific writing
  keyword: science, writing, team shrub, project scrub, dataizcool
  page-navigation: true
  sidebar: 
    logo: TeamShrubLogo.png
    search: true
  repo-url: https://github.com/ShrubHub/Scientific_method_class
  repo-subdir: book
  repo-branch: main
  repo-actions: [edit, issue, source]

  chapters:
    - index.qmd
    - Chapter-1.qmd
    - Chapter-2.qmd
    - Chapter-3.qmd
    - Chapter-4.qmd
    - Chapter-5.qmd

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    code-fold: false
    css: custom.css
    # mainfont: FiraCode
  # pdf:
  #   keep-tex: true
  #   documentclass: scrbook
  #   classoption: [paper=6in:9in,pagesize=pdftex,headinclude=on,footinclude=on,12pt]
  #   include-in-header:
  #     text: |
  #       \usepackage{inkscape}
  #       \usepackage{fvextra}
  #       \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
  #       \areaset[0.50in]{4.5in}{8in}
  #   include-before-body:
  #     text: |
  #       \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
  #          showspaces = false,
  #          showtabs = false,
  #          breaksymbolleft={},
  #          breaklines
  #          % Note: setting commandchars=\\\{\} here will cause an error 
  #       }  
  #   fig-pos: 'H'
